// Importing FontAwesome
import '@fortawesome/fontawesome-free/css/all.min.css';
import '../assets/styles/globals.css'

import NavBar from './_components/_nested_components/NavBar';

import Footer from './_components/Footer';

import { Changa_One , Roboto } from "next/font/google";

const changa_one = Changa_One({
  weight: ["400"],
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400" , "100" , "200" , "300" , "500" , "600" , "800" ],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${changa_one.className} ${roboto.className}`}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
